#' myoption
#'
#' All options I have used.
#'
#' @param no param need.
#' 
#' @return None
#'
#' @author Rui Chen (crotoc@gmail.com)
#'
#' @examples
#' option <- myoption()
#' @import 
#' optparse
#' @export
#' 
#'
#' 
#'

myoption <- function(){
    option <- list()
    option$general <- list(
        make_option(c("-i","--input"), action="store",
                    default="1",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("-o","--output"), action="store",
                    default=1,
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--dir_out"), action="store",
                    default="out",
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--header"), action="store",
                    default=FALSE,
                    type="logical",
                    help="number options [default: %default]"),
        make_option(c("-n","--number"), action="store",
                    default=1,
                    type="integer",
                    help="number options [default: %default]"),
        make_option(c("--example"), action="store_true",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--save_RData"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--test"), action="store_true",
                    default=FALSE,
                    help="Print little output"),
        make_option(c("-v", "--verbose"), action="store_true",
                    type="logical",
                    default=FALSE,
                    help="Print extra output [default %default]"),
        make_option(c("--progress_bar"),action="store",
                    default=FALSE,
                    type='logical',help="Progressing Bar [default: %default]"),
        make_option(c("--threads"), action="store",
                    default=5,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--digits"), action="store",
                    default=3,
                    type="integer",
                    help=" [default: %default]")
    )

    option$table <- list(
        make_option(c("--grp"), action="store",
                    default=0,
                    type="integer",
                    help=" grp col [default: %default]"),
        make_option(c("-x","--x"), action="store",
                    default=1,
                    type="integer",
                    help="number options [default: %default]"),
        make_option(c("-y","--y"), action="store",
                    default=2,
                    type="integer",
                    help="number options [default: %default]"),
        make_option(c("--value"), action="store",
                    default=12,
                    type="integer",
                    help=" value col [default: %default]"),
        make_option(c("--table"), action="store",
                    default=TRUE,
                    type="logical",
                    help="Output file [default: %default]")
    )

    option$plot <- list(
        make_option(c("--returnObject"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--ggobject"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--plot2file"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--strip_position"), action="store",
                    default="top",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--scale_x_log2"), action="store",
                    default=0,
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--scale_y_log2"), action="store",
                    default=0,
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--facetsort"), action="store",
                    default="increasing",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--xsort"), action="store",
                    default="increasing",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--strip_text_y_angle"), action="store",
                    default=90,
                    type="double",
                    help=" [default: %default]"),
        make_option(c("--rowfacet"), action="store",
                    default=TRUE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--annotation"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--xintercept"), action="store",
                    default=0,
                    type="double",
                    help="Horizonal line [default: %default]"),
        make_option(c("--yintercept"), action="store",
                    default=0,
                    type="double",
                    help="Vertical line [default: %default]"),
        make_option(c("--abline"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--slope"), action="store",
                    default=0,
                    type="double",
                    help=" [default: %default]"),
        make_option(c("--intercept"), action="store",
                    default=0,
                    type="double",
                    help=" [default: %default]"),
        make_option(c("--observation"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--fontsize"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--fontfamily"), action="store",
                    default="Times",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--pointshape"), action="store",
                    default=21,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--pointsize"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--lollipop"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--wrap"), action="store",
                    default=TRUE,
                    type="logical",
                    help="TRUE is facet_wrap and FALSE is facet_grid [default: %default]"),
        make_option(c("--ignore_col"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--mark_col"), action="store",
                    default="NULL",
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--mark_text_col"), action="store",
                    default=0,
                    type="integer",
                    help="text label col [default: %default]"),
        make_option(c("--legend_position"), action="store",
                    default="bottom",
                    type="character",
                    help="bottom, top, left, right, NULL [default: %default]"),
        make_option(c("--legend_direction"), action="store",
                    default="vertical",
                    type="character",
                    help="legend direction: vertical, horizontal [default: %default]"),
        make_option(c("--legend_ncol"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--legend_nrow"), action="store",
                    default=3,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--strip_angle"), action="store",
                    default=0,
                    type='double', help="Width [default: %default]"),
        make_option(c("--color"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--bin"), action="store",
                    default=30,
                    type="integer",
                    help="number options [default: %default]"),
        make_option(c("--vertical_line"), action="store",
                    default=NA,
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--mark_tissue"), action="store",
                    default="NULL",
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--mark_panel"), action="store",
                    default="NULL",
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--ncol"), action="store",
                    default=10,
                    type="integer",
                    help="number options [default: %default]"),
        make_option(c("--nrow"), action="store",
                    default=3,
                    type="integer",
                    help="number options [default: %default]"),
        make_option(c("--jitter"), action="store",
                    default=FALSE,
                    type="logical",
                    help="number options [default: %default]"),
        make_option(c("--quantile"), action="store",
                    default=0.05,
                    type="double",
                    help="number options [default: %default]"),
        make_option(c("--type"), action="store",
                    default="boxplot",
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--ext"), action="store",
                    default="pdf",
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--facet"), action="store",
                    default=0,
                    type="integer",
                    help="Output file [default: %default]"),
        make_option(c("--facet_grid"), action="store",
                    default=0,
                    type="character",
                    help="Output file [default: %default]"),
        make_option(c("--scale"), action="store",
                    default="fixed",
                    type="character",
                    help="fixed free free_x free_y [default: %default]"),
        make_option(c("--space"), action="store",
                    default="fixed",
                    type="character",
                    help="fixed free free_x free_y [default: %default]"),
        make_option(c("--drop"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--width"), action="store",
                    default=12,
                    type='double', help="Width [default: %default]"),
        make_option(c("--height"), action="store",
                    default=15,
                    type='double', help="Heigh [default: %default]"),
        make_option(c("--res"), action="store",
                    default=200,
                    type='integer', help="resolution [default: %default]"),
        make_option(c("--alpha"), action="store",
                    default=0.5,
                    type='double', help="Width [default: %default]"),
        make_option(c("--pal"), action="store",
                    default="Set2",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--ylim"), action="store",
                    default="NULL",
                    type='character', help="ylim [default: %default]"),
        make_option(c("--xlim"), action="store",
                    default="NULL",
                    type='character', help="ylim [default: %default]"),
        make_option(c("--ylab"), action="store",
                    default="NULL",
                    type='character', help="ylab [default: %default]"),
        make_option(c("--xlab"), action="store",
                    default="NULL",
                    type='character', help="xlab [default: %default]"),
        make_option(c("--col_point"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_error"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_perror"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_nerror"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]")
    )


    option$gwas <- list(
        make_option(c("--gwas"), action="store",
                    default="~/chenr6/gibbs/withoutDNM/out/SCZ_new_98_loci.bed",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--col_gwas_chr"), action="store",
                    default=2,
                    type="integer",
                    help="column of gwas chr [default: %default]"),
        make_option(c("--col_gwas_start"), action="store",
                    default=3,
                    type="integer",
                    help="start position of gwas loci [default: %default]"),
        make_option(c("--col_gwas_end"), action="store",
                    default=3,
                    type="integer",
                    help="end position of gwas loci [default: %default]"),
        make_option(c("--col_gwas_snp"), action="store",
                    default=1,
                    type="integer",
                    help="snp id of gwas loci [default: %default]"),
        make_option(c("--col_gwas_p"), action="store",
                    default=4,
                    type="integer",
                    help="snp id of gwas loci [default: %default]")
    )

    option$snp <- list(
        make_option(c("--col_chr"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_pos"), action="store",
                    default=3,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_snp"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--maf"), action="store",
                    default=0.1,
                    type="double",
                    help="+/- maf [default: %default]")
    )
    

    option$summary <- list(
        make_option(c("--summary_mode"), action="store",
                    default="scz",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--summary_stats"), action="store",
                    default="/gpfs23/scratch/cgg/chenr6/Database/PGC/scz2/scz2.snp.results.txt.RData",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--col_sum_chr"), action="store",
                    default=1,
                    type="integer",
                    help="chr col of summary [default: %default]"),
        make_option(c("--col_sum_start"), action="store",
                    default=5,
                    type="integer",
                    help="start pos of summary [default: %default]"),
        make_option(c("--col_sum_end"), action="store",
                    default=5,
                    type="integer",
                    help="end pos of summary [default: %default]"),
        make_option(c("--col_sum_p"), action="store",
                    default=9,
                    type="integer",
                    help="p value of summary [default: %default]"),
        make_option(c("--col_sum_snp"), action="store",
                    default=2,
                    type="integer",
                    help="p value of summary [default: %default]")
    )

    option$gibbsrank <- list(
        make_option(c("--gibbsrank"), action="store",
                    default="/gpfs23/scratch/cgg/chenr6/gibbs/6feature/out/SCZ_gibbs_sampling_go_rp_0.3_frequency.fmt.rank.pprank_disrank",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--col_gibbsrank_snp"), action="store",
                    default=3,
                    type="integer",
                    help="col of snp id of gibbs result [default: %default]"),
        make_option(c("--col_gibbsrank_gene"), action="store",
                    default=1,
                    type="integer",
                    help="gene col of gibbs result [default: %default]"),
        make_option(c("--col_gibbsrank_p"), action="store",
                    default=2,
                    type="integer",
                    help="p col of gibbs result [default: %default]"),
        make_option(c("--col_gibbsrank_ensembl"), action="store",
                    default=15,
                    type="integer",
                    help="ensembl id of gibbs result [default: %default]")
    )

    option$highc <- list(
        make_option(c("--highc_mode"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--highc"), action="store",
                    default="~/chenr6/gibbs/HiC/scz_cp_pooled.txt",
                    type="character",
                    help="Input file [default: %default]"),
        make_option(c("--col_bait_chr"), action="store",
                    default=1,
                    type="integer",
                    help="Chromosome [default: %default]"),
        make_option(c("--col_bait_start"), action="store",
                    default=2,
                    type="integer",
                    help="The bait start position [default: %default]"),
        make_option(c("--col_bait_end"), action="store",
                    default=3,
                    type="integer",
                    help="The bait end position [default: %default]"),
        make_option(c("--col_region_chr"), action="store",
                    default=1,
                    type="integer",
                    help="Chromosome [default: %default]"),
        make_option(c("--col_region_start"), action="store",
                    default=4,
                    type="integer",
                    help="Start position of interacting region [default: %default]"),
        make_option(c("--col_region_end"), action="store",
                    default=5,
                    type="integer",
                    help="End position of interacting region [default: %default]"),
        make_option(c("--col_bait_p"), action="store",
                    default=6,
                    type="integer",
                    help=" p value of the interaction[default: %default]"),
        make_option(c("--col_bait_ensembl"), action="store",
                    default=7,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_bait_gene"), action="store",
                    default=8,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_enh_chr"), action="store",
                    default=1,
                    type="integer",
                    help="Chromosome [default: %default]")
    )

    option$enhancer <- list(
        make_option(c("--col_enh_start"), action="store",
                    default=2,
                    type="integer",
                    help="The bait start position [default: %default]"),
        make_option(c("--col_enh_end"), action="store",
                    default=3,
                    type="integer",
                    help="The bait end position [default: %default]"),
        make_option(c("--col_enh_p"), action="store",
                    default=6,
                    type="integer",
                    help="correlation of ehn and tss [default: %default]"),
        make_option(c("--col_tss_chr"), action="store",
                    default=1,
                    type="integer",
                    help="Chromosome [default: %default]"),
        make_option(c("--col_tss_start"), action="store",
                    default=4,
                    type="integer",
                    help="Start position of interacting region [default: %default]"),
        make_option(c("--col_tss_end"), action="store",
                    default=5,
                    type="integer",
                    help="End position of interacting region [default: %default]")
    )

    option$heatmap <- list(
        make_option(c("--threshold"), action="store",
                    default=0,
                    type="numeric",
                    help=" [default: %default]"),
        make_option(c("--row_cluster"), action="store",
                    default="cor",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--col_cluster"), action="store",
                    default="cor",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--border"), action="store",
                    default="none",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--valuename"), action="store",
                    default="scaled",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--ycol"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--xcol"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--scaled"), action="store",
                    default="scalemax",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--preprocessing"), action="store",
                    default="none",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--row_k"), action="store",
                    default=5,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_k"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--midpoint"), action="store",
                    default="median",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--interval"), action="store",
                    default=,
                    type="integer",
                    help=" [default: %default]"),
####################################################################
#######		row meta key
#####################################################################
        make_option(c("--rowmeta"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--rowmeta_header"), action="store",
                    default=TRUE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--rowmeta_cols"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--rowmeta_sort_by"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--rowmeta_ycol"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--rowmeta_width"), action="store",
                    default=1,
                    type="numeric",
                    help=" [default: %default]"),
        make_option(c("--rowmeta_clustercol"), action="store",
                    default=0,
                    type="numeric",
                    help=" [default: %default]"),
####################################################################
#######		row meta text
#####################################################################
        make_option(c("--rowmetatext"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_header"), action="store",
                    default=TRUE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_cols"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_sort_by"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_ycol"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_fillcol"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_width"), action="store",
                    default=2,
                    type="numeric",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_legend_nrow"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--rowmetatext_legend_ncol"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
####################################################################
#######		col meta key
#####################################################################
        make_option(c("--colmeta"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--colmeta_header"), action="store",
                    default=TRUE,
                    type="logical",
                    help=" [default: %default]"),
        make_option(c("--colmeta_cols"), action="store",
                    default="NULL",
                    type="character",
                    help=" [default: %default]"),
        make_option(c("--colmeta_sort_by"), action="store",
                    default=0,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--colmeta_ycol"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--colmeta_grp"), action="store",
                    default=2,
                    type="integer",
                    help=" [default: %default]"),
####################################################################
#######	 row dendogram width	
#####################################################################
        make_option(c("--row_dd_width"), action="store",
                    default=10,
                    type="integer",
                    help=" [default: %default]"),
####################################################################
#######		row key width
#####################################################################
        make_option(c("--row_key_width"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--heatmap_width"), action="store",
                    default=20,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_dd_height"), action="store",
                    default=10,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--col_key_height"), action="store",
                    default=1,
                    type="integer",
                    help=" [default: %default]"),
        make_option(c("--heatmap_height"), action="store",
                    default=20,
                    type="integer",
                    help=" [default: %default]"),
####################################################################
#######		plot by cluster in different pages
#####################################################################
        make_option(c("--clusterplot"), action="store",
                    default=FALSE,
                    type="logical",
                    help=" [default: %default]"),
####################################################################
#######		go heatmap plot
#####################################################################
        make_option(c("--gmtfile"), action="store",
                    default="/fs0/chenr6/Database_fs0/GO/is_a.partof.regulates/fmt/go.biological_process",
                    type="character",
                    help=" [default: %default]")
    )
    return(option)
}
