option$heatmap <- list(
    make_option(c("--high"), action="store",
                default=NA,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--low"), action="store",
                default=NA,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--fig_legend_ratio"), action="store",
                default="5,1",
                type="character",
                help=" [default: %default]"),
    make_option(c("--ncolor"), action="store",
                default=2,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--cutreeDynamicTree"), action="store",
                default="hybrid",
                type="character",
                help=" [default: %default]"),
    make_option(c("--minClusterSize"), action="store",
                default=10,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--deepSplit"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--cutHeight"), action="store",
                default=0.99,
                type="double",
                help=" [default: %default]"),
    make_option(c("--row_cluster"), action="store",
                default="cor",
                type="character",
                help=" [default: %default]"),
    make_option(c("--col_cluster"), action="store",
                default="cor",
                type="character",
                help=" [default: %default]"),
    make_option(c("--border"), action="store",
                default="none",
                type="character",
                help=" [default: %default]"),
    make_option(c("--valuename"), action="store",
                default="scaled",
                type="character",
                help=" [default: %default]"),
    make_option(c("--scaled"), action="store",
                default="scalemax",
                type="character",
                help=" [default: %default]"),
    make_option(c("--preprocessing"), action="store",
                default="none",
                type="character",
                help=" [default: %default]"),
    make_option(c("--row_k"), action="store",
                default=5,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--col_k"), action="store",
                default=2,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--midpoint"), action="store",
                default="median",
                type="character",
                help=" [default: %default]"),
    make_option(c("--interval"), action="store",
                default=,
                type="integer",
                help=" [default: %default]"),
####################################################################
#######		row meta key
#####################################################################
    make_option(c("--rowmeta"), action="store",
                default="NULL",
                type="character",
                help=" [default: %default]"),
    make_option(c("--rowmeta_header"), action="store",
                default=TRUE,
                type="logical",
                help=" [default: %default]"),
    make_option(c("--rowmeta_cols"), action="store",
                default="NULL",
                type="character",
                help=" [default: %default]"),
    make_option(c("--rowmeta_sort_by"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--rowmeta_ycol"), action="store",
                default=1,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--rowmeta_width"), action="store",
                default=1,
                type="numeric",
                help=" [default: %default]"),
    make_option(c("--rowmeta_clustercol"), action="store",
                default=0,
                type="numeric",
                help=" [default: %default]"),
####################################################################
#######		row meta text
#####################################################################
    make_option(c("--rowmetatext"), action="store",
                default="NULL",
                type="character",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_header"), action="store",
                default=TRUE,
                type="logical",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_cols"), action="store",
                default="NULL",
                type="character",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_sort_by"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_ycol"), action="store",
                default=1,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_fillcol"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_width"), action="store",
                default=2,
                type="numeric",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_legend_nrow"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--rowmetatext_legend_ncol"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
####################################################################
#######		col meta key
#####################################################################
    make_option(c("--colmeta"), action="store",
                default="NULL",
                type="character",
                help=" [default: %default]"),
    make_option(c("--colmeta_header"), action="store",
                default=TRUE,
                type="logical",
                help=" [default: %default]"),
    make_option(c("--colmeta_cols"), action="store",
                default="NULL",
                type="character",
                help=" [default: %default]"),
    make_option(c("--colmeta_sort_by"), action="store",
                default=0,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--colmeta_ycol"), action="store",
                default=1,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--colmeta_grp"), action="store",
                default=2,
                type="integer",
                help=" [default: %default]"),
####################################################################
#######	 row dendogram width	
#####################################################################
    make_option(c("--row_dd_width"), action="store",
                default=10,
                type="integer",
                help=" [default: %default]"),
####################################################################
#######		row key width
#####################################################################
    make_option(c("--row_key_width"), action="store",
                default=1,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--heatmap_width"), action="store",
                default=20,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--col_dd_height"), action="store",
                default=10,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--col_key_height"), action="store",
                default=1,
                type="integer",
                help=" [default: %default]"),
    make_option(c("--heatmap_height"), action="store",
                default=20,
                type="integer",
                help=" [default: %default]"),
####################################################################
#######		plot by cluster in different pages
#####################################################################
    make_option(c("--clusterplot"), action="store",
                default=FALSE,
                type="logical",
                help=" [default: %default]"),
####################################################################
#######		go heatmap plot
#####################################################################
    make_option(c("--gmtfile"), action="store",
                default="/fs0/chenr6/Database_fs0/GO/is_a.partof.regulates/fmt/go.biological_process",
                type="character",
                help=" [default: %default]")
)
